# Generated by Django 2.2.4 on 2023-02-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surverys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='users',
            field=models.ManyToManyField(related_name='users', to='users.User'),
        ),
    ]
