# Generated by Django 2.2.4 on 2023-03-03 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0002_auto_20230303_0237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
